#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# autostart apps
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
$HOME/.config/polybar/launch.sh &
xbanish &
# bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
# if [[ $xrandr -q | grep -i 'hdmi-2 connected']]; then
#   xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-2 --mode 1920x1080 --rotate normal --right-of eDP-1
# fi

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 
# bspc monitor HDMI-2 -d 5 6 7 8 

bspc config border_width         0 
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
